---
- name: Create a sandbox instance
  hosts: localhost
  remote_user: root
  become: true
  gather_facts: False
  vars:
    keypair: mynewkey123 
    instance_type: t2.micro 
    #security_group: my_securitygroup
    image: ami-0b500ef59d8335eee  
    region: us-east-2
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ keypair }}"
         #group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-e7cfa39d 
         assign_public_ip: yes
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        delay: 60
        timeout: 320
      with_items: "{{ ec2.instances }}"
       
    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        delay: 60
        timeout: 320
      with_items: "{{ ec2.instances }}"
